services:
    # app.form.registration:
    #     class: Application\Sonata\UserBundle\Form\RegistrationType
    #     arguments: [%fos_user.model.user.class%,'@doctrine.orm.entity_manager']
    #     tags:
    #         - { name: form.type, alias: application_sonata_user_registration }

    app.form.registration:
        class: Application\Sonata\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
        arguments: [ '@doctrine.orm.entity_manager']
        
    app.form.profile:
        class: Application\Sonata\UserBundle\Form\UserType
        tags:
            - { name: form.type, alias: application_sonata_user_profile }
        arguments: [ '@doctrine.orm.entity_manager']

    app.security.authentication_handler:
        class: Application\Sonata\UserBundle\EventHandler\AuthenticationHandler
        public: false
        arguments:
            - "@router"
            - "@session"